'use strict';

module.exports = {
  Room: false,
  RoomPosition: false,
  RoomObject: false,
  ConstructionSite: false,
  Creep: false,
  Flag: false,
  Mineral: false,
  Nuke: false,
  Resource: false,
  Energy: false,
  Source: false,
  Structure: false,
  OwnedStructure: false,
  StructureController: false,
  StructureExtension: false,
  StructureExtractor: false,
  StructureKeeperLair: false,
  StructureLab: false,
  StructureLink: false,
  StructureNuker: false,
  StructureObserver: false,
  StructurePowerBank: false,
  StructurePowerSpawn: false,
  StructureRampart: false,
  StructureSpawn: false,
  Spawn: false,
  StructureStorage: false,
  StructureTerminal: false,
  StructureTower: false,
  StructureContainer: false,
  StructurePortal: false,
  StructureRoad: false,
  StructureWall: false,
};
